seed: &seed 42

environment: # Overrides default environment configs (see pygpudrive/env/config.py)
  ego_state: true
  road_map_obs: true
  partner_obs: true
  norm_obs: true
  max_controlled_agents: 64 # Maximum number of agents controlled by the model. Make sure this aligns with the variable kMaxAgentCount in src/consts.hpp
  num_worlds: &num_worlds 800 # Number of parallel environments
  lidar_obs: false # NOTE: Setting this to true currently turns of the other observation types
  collision_weight: -0.75
  off_road_weight: -0.75
  goal_achieved_weight: 1.0
  obs_radius: 50.0 # Visibility radius of the agents
  polyline_reduction_threshold: 0.1 # Rate at which to sample points from the polyline (0 is use all closest points, 1 maximum sparsity), needs to be balanced with kMaxAgentMapObservationsCount
  dynamics_model: "delta_local"
  collision_behavior: "ignore" # Options: "remove", "stop", "ignore"
  remove_non_vehicles: true # If false, all agents are included (vehicles, pedestrians, cyclists)
  init_steps: 0
  reward_type: "weighted_combination"
  dist_to_goal_threshold: 2.0
  controllable_agent_selection: "no_static"
  mirror_x: false
  # Versatile Behavior Diffusion (VBD): This will slow down training
  use_vbd: false
  vbd_model_path: "gpudrive/integrations/vbd/weights/epoch=18.ckpt"
  vbd_trajectory_weight: 0.1 # Importance of distance to the vbd trajectories in the reward function
  vbd_in_obs: false

data_loader:
  root: PATH/TO/DATASET
  batch_size: *num_worlds
  dataset_size: 20_000
  sample_with_replacement: false
  file_prefix: ""
  seed: *seed
  shuffle: false

train:
  exp_id: eval_bc_boston_sp_singapore_valid_1600 # Set dynamically in the script if needed
  seed: *seed
  cpu_offload: false
  device: "cuda"  # Dynamically set to cuda if available, else cpu
  bptt_horizon: 1
  compile: false
  compile_mode: "reduce-overhead"
  continue_training: true
  model_cpt_dir: PATH/TO/CHECKPOINT
  action_type: "multi_discrete"
  # # # Evaluate Data sampling # # #
  resample_scenes: true
  resample_interval: 1_000_000
  sample_with_replacement: true
  shuffle_dataset: false

  # # # BC Training # # #
  torch_deterministic: false
  total_timesteps: 1_000_000_000
  batch_size: 256
  learning_rate: 1e-3
  weight_decay: 1e-2
  anneal_lr: false
  epochs: 200

  # # # BC Evaluation # # #
  eval_freq: 10
  eval_num_episodes: 500

  # # # Network # # #
  network:
    input_dim: 64 # Embedding of the input features
    hidden_dim: 128 # Latent dimension
    dropout: 0.01
    class_name: "NeuralNet"
    num_parameters: ??? # Total trainable parameters, to be filled at runtime

  # # # Checkpointing # # #
  checkpoint_interval: 50 # Save policy every k iterations
  checkpoint_path: "./runs"

  # # # Rendering # # #
  render: false # Determines whether to render the environment (note: will slow down training)
  render_3d: true # Render simulator state in 3d or 2d
  render_interval: 1 # Render every k iterations
  render_k_scenarios: 10 # Number of scenarios to render
  render_format: "mp4" # Options: gif, mp4
  render_fps: 15 # Frames per second
  zoom_radius: 50

vec:
  backend: "native" # Only native is currently supported
  num_workers: 1
  env_batch_size: 1
  zero_copy: false

